project_id = "kmmdzwoidakmbekqvkmq"

[functions.merge-user-data]
verify_jwt = false

[functions.check-imported-user]
verify_jwt = false

[functions.migrate-imported-user]
verify_jwt = false

[functions.list-all-users]
verify_jwt = false

[functions.system-health-check]
verify_jwt = false